- name: "Hosts"
  hosts: all
  become: yes

  tasks:
   - name: "Docker | apt-get install"
     apt: name={{item}} state=present
     with_items:
     - apt-transport-https
     - ca-certificates
     - nfs-common
     - htop
     - cifs-utils
     register: aptget

   - name: "Docker | key"
     command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

   - name: "Docker | Create file docker.list Ubuntu 16"
     template: src=temp-docker.list-16 dest=/etc/apt/sources.list.d/docker.list owner=root mode=644 backup=yes
     register: repositorio
     when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"

   - name: "Docker | Create file docker.list Ubuntu 14"
     template: src=temp-docker.list-14 dest=/etc/apt/sources.list.d/docker.list owner=root mode=644 backup=yes
     register: repositorio
     when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"
  
   - name: "Docker | apt-get update"
     apt: update_cache=yes

   - name: "Docker | purge lxc-docker"
     command: apt-get purge lxc-docker
     ignore_errors: yes

   - name: "Docker | apt-get install linux-image"
     apt: name={{item}} state=present
     with_items:
     - linux-image-extra-virtual

   - name: "Docker | apt-get update"
     apt: update_cache=yes

   - name: "Docker | apt-get install docker-engine"
     apt: name={{item}} state=present
     with_items:
     - docker-engine
     when: repositorio|success

   - name: "Docker | Install docker-compose"
     shell: curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
     ignore_errors: yes
 
   - name: "Docker | Adjustment permission docker-compose"
     file: path=/usr/local/bin/docker-compose mode=755
     ignore_errors: yes

   - name: "Docker | Enable Docker init.d"
     service: name=docker enabled=yes
     ignore_errors: yes

   - name: "Docker | Restart Docker"
     service: name=docker state=restarted
     ignore_errors: yes

   - name: "Docker | Install Weave network"
     get_url:
      url: http://git.io/weave
      dest: /usr/local/bin/weave
     ignore_errors: yes

   - name: "Docker | Adjustment permission weave"
     file: path=/usr/local/bin/weave mode=755
     ignore_errors: yes

   - name: "Docker | Install Rexray"
     shell: curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable
     ignore_errors: yes
