- name: "Hosts"
  hosts: all
  become: yes

  tasks:
   - name: "Docker | apt-get install"
     apt: name={{item}} state=present
     with_items:
     - apt-transport-https
     - ca-certificates
     - nfs-common
     - htop
     - cifs-utils
     register: aptget

   - name: "Docker | key"
     apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

   - name: "Docker | Add docker apt repository"
     apt_repository: repo="deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main" state=present

   - name: "Docker | apt-get update"
     apt: update_cache=yes

   - name: "Docker | purge lxc-docker"
     command: apt-get purge lxc-docker
     ignore_errors: yes

   - name: "Docker | apt-get install linux-image"
     apt: name={{item}} state=present
     with_items:
     - linux-image-extra-virtual
     ignore_errors: yes

   - name: "Docker | apt-get update"
     apt: update_cache=yes

   - name: "Docker | apt-get install docker-engine"
     apt: name={{item}} state=present
     with_items:
     - docker-engine

   - name: "Docker | Install docker-compose"
     shell: curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
     ignore_errors: yes
 
   - name: "Docker | Adjustment permission docker-compose"
     file: path=/usr/local/bin/docker-compose mode=755
     ignore_errors: yes

   - name: "Docker | Enable Docker init.d"
     service: name=docker enabled=yes
     ignore_errors: yes

   - name: "Docker | Create daemon.json"
     template: src=../templates/temp-daemon.json dest=/etc/docker/daemon.json owner=root mode=644 backup=yes
     register: daemon_json
     when: aptget|success

   - name: "Docker | Restart Docker"
     service: name=docker state=restarted
     ignore_errors: yes

   - name: "Docker | Install Weave network"
     get_url:
      url: http://git.io/weave
      dest: /usr/local/bin/weave
     ignore_errors: yes

   - name: "Docker | Adjustment permission weave"
     file: path=/usr/local/bin/weave mode=755
     ignore_errors: yes

   - name: "Docker | Install Rexray"
     shell: curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable
     ignore_errors: yes


